// generated by Proto2Typescript. do not touch!

declare module channer {
	interface ProtoBufModel {
		toArrayBuffer(): ArrayBuffer;
		//toBuffer(): NodeBuffer;
		//encode(): ByteBuffer;
		toBase64(): string;
		toString(): string;
	}

	export interface ProtoBufBuilder {
		Login: LoginBuilder;
		MsgHLC: MsgHLCBuilder;
		MsgOptions: MsgOptionsBuilder;
		Msg: MsgBuilder;
		Hoge: HogeBuilder;
		
	}
}

declare module channer {

	export interface Login extends ProtoBufModel {
		hash: string;
		getHash() : string;
		setHash(hash : string): void;
		ts: number;
		getTs() : number;
		setTs(ts : number): void;
		
	}
	
	export interface LoginBuilder {
		new(): Login;
		decode(buffer: ArrayBuffer) : Login;
		//decode(buffer: NodeBuffer) : Login;
		//decode(buffer: ByteArrayBuffer) : Login;
		decode64(buffer: string) : Login;
		
	}	
}

declare module channer {

	export interface MsgHLC extends ProtoBufModel {
		ts_sec: number;
		getTsSec() : number;
		setTsSec(tsSec : number): void;
		logical_ts: number;
		getLogicalTs() : number;
		setLogicalTs(logicalTs : number): void;
		
	}
	
	export interface MsgHLCBuilder {
		new(): MsgHLC;
		decode(buffer: ArrayBuffer) : MsgHLC;
		//decode(buffer: NodeBuffer) : MsgHLC;
		//decode(buffer: ByteArrayBuffer) : MsgHLC;
		decode64(buffer: string) : MsgHLC;
		
	}	
}

declare module channer {

	export interface MsgOptions extends ProtoBufModel {
		refers: MsgHLC[];
		getRefers() : MsgHLC[];
		setRefers(refers : MsgHLC[]): void;
		no_fetch_url?: boolean;
		getNoFetchUrl() : boolean;
		setNoFetchUrl(noFetchUrl : boolean): void;
		
	}
	
	export interface MsgOptionsBuilder {
		new(): MsgOptions;
		decode(buffer: ArrayBuffer) : MsgOptions;
		//decode(buffer: NodeBuffer) : MsgOptions;
		//decode(buffer: ByteArrayBuffer) : MsgOptions;
		decode64(buffer: string) : MsgOptions;
		
	}	
}

declare module channer {

	export interface Msg extends ProtoBufModel {
		text: string;
		getText() : string;
		setText(text : string): void;
		options?: MsgOptions;
		getOptions() : MsgOptions;
		setOptions(options : MsgOptions): void;
		
	}
	
	export interface MsgBuilder {
		new(): Msg;
		decode(buffer: ArrayBuffer) : Msg;
		//decode(buffer: NodeBuffer) : Msg;
		//decode(buffer: ByteArrayBuffer) : Msg;
		decode64(buffer: string) : Msg;
		
	}	
}

declare module channer {

	export interface Hoge extends ProtoBufModel {
		data: string;
		getData() : string;
		setData(data : string): void;
		
	}
	
	export interface HogeBuilder {
		new(): Hoge;
		decode(buffer: ArrayBuffer) : Hoge;
		//decode(buffer: NodeBuffer) : Hoge;
		//decode(buffer: ByteArrayBuffer) : Hoge;
		decode64(buffer: string) : Hoge;
		
	}	
}
